# Generated by Django 4.2 on 2023-04-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_name_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, default='un-categorized', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='un-categorized', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='un-branded', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='no-product', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='un-titled-product', max_length=250),
        ),
    ]
